baseURL: https://javimostoles.github.io
languageCode: es-ES
title: Javi Pérez
theme: "PaperMod"

params:
  homeInfoParams:
    Title: Bienvenidos 😎
    Content: En este blog iré compartiendo mis aprendizajes sobre logseq con el objetivo de seguir la metodología [BASB (Build a Second Brain) de Tiago Forte](https://www.buildingasecondbrain.com/)

  socialIcons: # optional
    - name: "github"
      url: "https://github.com/javimostoles"
    - name: "twitter"
      url: "https://twitter.com/javimostoles"
    # - name: "kofi"
    #   url: "https://buymeacoffee.com/XXX"
    - name: "rss"
     url: "https://javimostoles.github.io/index.xml"
  ShowReadingTime: true
  author: "Javi Pérez"
  contact: "javier.perezdepedro@gmail.com"
  feedlinks: true
  copyright: "This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/)."
  mobileMenu: true

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
  section:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Etiquetas
      url: /tags/
      weight: 20
    - identifier: search
      name: Búsqueda
      url: /search/
      weight: 20
    - identifier: archive
      name: Archivo
      url: /archives/
      weight: 20
