baseURL: https://javimostoles.github.io/
languageCode: es-ES
title: Learning by doing
theme: "PaperMod"

params:
    homeInfoParams:
        Title: Bienvenidos 👋
        Content: Blog personal sobre Logseq

    socialIcons: # optional
        - name: "github"
          url: "https://github.com/javimostoles"
        - name: "twitter"
          url: "https://twitter.com/javimostoles"
        - name: "rss"
          url: "https://javimostoles.github.io/index.xml"
    ShowReadingTime: true
    author: "Javi"

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

menu:
    main:
        # - identifier: categories
        #   name: Categories
        #   url: /categories/
        #   weight: 10
        # - identifier: tags
        #   name: Tags
        #   url: /tags/
        #   weight: 20
        - identifier: graph
          name: Grafo
          url: 'https://javimostoles.github.io/graph/#/graph'
          weight: 10
        - identifier: archive
          name: Archivo
          url: /archives/
          weight: 20
        - identifier: Búsqueda
          name: Búsqueda
          url: /search/
          weight: 30
        
